import { Link, NavLink, useLocation } from 'react-router-dom'
import { ArrowRight, Bell, BookOpen, BriefcaseBusiness, ChartNoAxesCombined, Check, ChevronDown, ChevronRight, Code2, Compass, Flame, Home, Layers3, ListChecks, Menu, MoreHorizontal, Settings, Sparkles, UserRound, X, BrainCircuit } from './icons'
import { useState } from 'react'
import { load } from '../utils/storage'

export function Brand(){return <Link className="brand" to="/" aria-label="KGS AI home"><span className="brand-mark"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M8 24V10a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v3M8 17h9a4 4 0 0 1 0 8h-3m7-9 3-4 3 4"/><circle cx="8" cy="25" r="2"/></svg></span><span>KGS<span className="brand-ai">AI</span></span></Link>}
export function Button({children,variant='primary',icon:Icon,className='',...props}){return <button className={`button button-${variant} ${className}`} {...props}>{Icon&&<Icon size={16} />}{children}</button>}
export function Badge({children,tone='neutral'}){return <span className={`badge badge-${tone}`}>{children}</span>}
export function ProgressBar({value,color='violet'}){return <div className={`progress-track progress-${color}`}><span style={{width:`${value}%`}}/></div>}
export function PageHeading({eyebrow,title,detail,action}){return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{detail&&<p>{detail}</p>}</div>{action}</div>}
export function StatCard({icon:Icon,label,value,note,color='violet'}){return <article className="stat-card"><span className={`stat-icon stat-${color}`}><Icon size={18}/></span><div className="stat-copy"><span>{label}</span><b>{value}</b><small>{note}</small></div></article>}
const items=[['Overview','/dashboard',Home],['My roadmap','/roadmap',Compass],['Learn','/learn/java-variables',BookOpen],['Practice','/practice',Code2],['Quizzes','/quiz/java-basics',ListChecks],['Projects','/projects',BriefcaseBusiness],['Progress','/progress',ChartNoAxesCombined],['AI tutor','/learn/java-variables#tutor',BrainCircuit]]
export function AppLayout({children}){const[open,setOpen]=useState(false);const location=useLocation();const unread=load('notifications',[]).some(n=>!n.read);const title=items.find(x=>location.pathname.startsWith(x[1].split('#')[0]))?.[0]||'Learning';return <div className="app-shell"><button className={`sidebar-scrim ${open?'scrim-visible':''}`} onClick={()=>setOpen(false)} aria-label="Close navigation"/><aside className={`app-sidebar ${open?'sidebar-open':''}`}><div className="sidebar-brand"><Brand/><button className="sidebar-close" onClick={()=>setOpen(false)} aria-label="Close menu"><X size={17}/></button></div><div className="workspace-switch"><span className="workspace-avatar">A</span><span><b>Alex's workspace</b><small>Personal learning</small></span><ChevronDown size={15}/></div><div className="sidebar-label">YOUR LEARNING</div><nav className="side-nav">{items.map(([label,to,Icon])=><NavLink onClick={()=>setOpen(false)} key={label} to={to} className={({isActive})=>`side-link ${isActive?'side-active':''}`}><Icon size={17}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-label">YOUR SPACE</div><nav className="side-nav"><NavLink onClick={()=>setOpen(false)} to="/notifications" className={({isActive})=>`side-link ${isActive?'side-active':''}`}><Bell size={17}/><span>Notifications</span>{unread&&<i className="nav-unread"/>}</NavLink><NavLink onClick={()=>setOpen(false)} to="/profile" className={({isActive})=>`side-link ${isActive?'side-active':''}`}><UserRound size={17}/><span>My profile</span></NavLink><NavLink onClick={()=>setOpen(false)} to="/settings" className={({isActive})=>`side-link ${isActive?'side-active':''}`}><Settings size={17}/><span>Settings</span></NavLink></nav><div className="sidebar-bottom"><div className="streak-panel"><Flame size={17}/><span><b>7 day streak</b><small>You're building a habit</small></span><MoreHorizontal size={17}/></div><Link to="/profile" className="user-row"><span className="user-avatar">AM</span><span><b>Alex Morgan</b><small>Beginner · Java</small></span></Link></div></aside><div className="app-main"><header className="app-topbar"><button className="mobile-menu" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={20}/></button><div className="breadcrumb"><span>Learning space</span><ChevronRight size={14}/><b>{title}</b></div><div className="topbar-actions"><label className="top-search"><span>⌕</span><input placeholder="Search lessons, topics..."/><kbd>⌘ K</kbd></label><Link to="/notifications" className="top-icon" aria-label="Notifications"><Bell size={18}/>{unread&&<i/>}</Link><Link to="/profile" className="top-avatar">AM</Link></div></header><main key={location.pathname} className="page-content">{children}</main></div></div>}
